# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eduardo/Documentos/Projetos/FreeAI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eduardo/Documentos/Projetos/FreeAI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduardo/Documentos/Projetos/FreeAI/CMakeFiles /home/eduardo/Documentos/Projetos/FreeAI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eduardo/Documentos/Projetos/FreeAI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FreeAI

# Build rule for target.
FreeAI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FreeAI
.PHONY : FreeAI

# fast build rule for target.
FreeAI/fast:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/build
.PHONY : FreeAI/fast

src/ag.o: src/ag.cpp.o

.PHONY : src/ag.o

# target to build an object file
src/ag.cpp.o:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/ag.cpp.o
.PHONY : src/ag.cpp.o

src/ag.i: src/ag.cpp.i

.PHONY : src/ag.i

# target to preprocess a source file
src/ag.cpp.i:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/ag.cpp.i
.PHONY : src/ag.cpp.i

src/ag.s: src/ag.cpp.s

.PHONY : src/ag.s

# target to generate assembly for a file
src/ag.cpp.s:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/ag.cpp.s
.PHONY : src/ag.cpp.s

src/individual.o: src/individual.cpp.o

.PHONY : src/individual.o

# target to build an object file
src/individual.cpp.o:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/individual.cpp.o
.PHONY : src/individual.cpp.o

src/individual.i: src/individual.cpp.i

.PHONY : src/individual.i

# target to preprocess a source file
src/individual.cpp.i:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/individual.cpp.i
.PHONY : src/individual.cpp.i

src/individual.s: src/individual.cpp.s

.PHONY : src/individual.s

# target to generate assembly for a file
src/individual.cpp.s:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/individual.cpp.s
.PHONY : src/individual.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/population.o: src/population.cpp.o

.PHONY : src/population.o

# target to build an object file
src/population.cpp.o:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/population.cpp.o
.PHONY : src/population.cpp.o

src/population.i: src/population.cpp.i

.PHONY : src/population.i

# target to preprocess a source file
src/population.cpp.i:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/population.cpp.i
.PHONY : src/population.cpp.i

src/population.s: src/population.cpp.s

.PHONY : src/population.s

# target to generate assembly for a file
src/population.cpp.s:
	$(MAKE) -f CMakeFiles/FreeAI.dir/build.make CMakeFiles/FreeAI.dir/src/population.cpp.s
.PHONY : src/population.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FreeAI"
	@echo "... src/ag.o"
	@echo "... src/ag.i"
	@echo "... src/ag.s"
	@echo "... src/individual.o"
	@echo "... src/individual.i"
	@echo "... src/individual.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/population.o"
	@echo "... src/population.i"
	@echo "... src/population.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

